version: '3.9'
services:
  database:
    image: postgres
    container_name: postgres 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
    - "5432:5432"